create table if not exists public.user_notification_preferences (
    user_id uuid primary key references auth.users(id) on delete cascade,
    analysis_ready_email boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    notification_type text not null,
    notification_date date not null,
    watchlist_symbols text[] not null default '{}',
    status text not null check (status in ('processing', 'sent', 'failed')),
    provider_message_id text,
    error_message text,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint notification_deliveries_user_type_date_key
        unique (user_id, notification_type, notification_date)
);

create index if not exists notification_deliveries_status_date_idx
    on public.notification_deliveries (status, notification_date desc);

alter table public.user_notification_preferences enable row level security;
alter table public.notification_deliveries enable row level security;

revoke all on table public.user_notification_preferences from anon;
revoke all on table public.notification_deliveries from anon;
grant select, insert, update on table public.user_notification_preferences to authenticated;
grant select on table public.notification_deliveries to authenticated;
grant all on table public.user_notification_preferences to service_role;
grant all on table public.notification_deliveries to service_role;
grant usage, select on sequence public.notification_deliveries_id_seq to service_role;

drop policy if exists "Users can read their email preference" on public.user_notification_preferences;
create policy "Users can read their email preference"
    on public.user_notification_preferences
    for select
    to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their email preference" on public.user_notification_preferences;
create policy "Users can create their email preference"
    on public.user_notification_preferences
    for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their email preference" on public.user_notification_preferences;
create policy "Users can update their email preference"
    on public.user_notification_preferences
    for update
    to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read their notification deliveries" on public.notification_deliveries;
create policy "Users can read their notification deliveries"
    on public.notification_deliveries
    for select
    to authenticated
    using ((select auth.uid()) = user_id);

notify pgrst, 'reload schema';
